config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#index"
  
  # Top画面
  resources :homes, only: [:index]

  # タレント画面
  resources :talents, only: [:index, :show]

  # ニュース画面
  resources :news, only: [:index]

  # オーディション画面
  resources :audition, only: [:index]

  # 会社概要画面
  resources :company, only: [:index]

  # お問い合わせ画面
  resources :contact, only: [:index]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :url, ImageUploader
  belongs_to :talent
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/talent.rb
class Talent < ApplicationRecord
  has_many :images, dependent: :destroy

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/audition_controller.rb
class AuditionController < ApplicationController
  def index
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @news = News.all.order(date: "ASC").page(params[:page]).per(10)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all.order(date: "ASC").page(params[:page]).per(10)
  end
end

app/controllers/talents_controller.rb
class TalentsController < ApplicationController
  def index
    @talents = Talent.all.order(created_at: "ASC")
  end

  def show
    @talents = Talent.all.order(created_at: "ASC")
    @talent = Talent.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/audition_helper.rb
module AuditionHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/talents_helper.rb
module TalentsHelper
end

app/views/audition/index.html.haml
= render 'homes/header'
.audition-wrapper
  .audition-wrapper__title
    Audition
  .audition-wrapper__sub-title
    コロンコロン株式会社では、常に新人募集を行っております。 俳優・モデル・タレント・アーティストを目指し、頑張りたい方のご応募をお待ちしております。
  .audition-wrapper__contents
    .audition-wrapper__contents__title
      タレント
    .audition-wrapper__contents__main
      %dl.article
        %dt 応募資格
        %dd 10代、20代の男女
      %dl.article
        %dt 応募方法
        %dd
          .audition-wrapper__contents__main__text
            郵送、またはメール送信で応募して下さい。
          .audition-wrapper__contents__main__title
            【E-mailでの応募】
          %ul.audition-wrapper__contents__main__list
            %li ・お名前
            %li ・年齢
            %li ・住所
            %li ・連絡先
            %li ・身長
            %li ・3サイズ
            %li ・志望動機
            %li ・目標
          .audition-wrapper__contents__main__text
            上記をメールに明記の上、写真2枚（バストアップ・全身1枚ずつ）を添付して
            %a{:href => "mailto:coroncoron@coron2.jp", class: "mail-link"} こちら
            からご応募下さい。
          .audition-wrapper__contents__main__title
            【郵送での応募】
          %ul.audition-wrapper__contents__main__list
            %li ・身長
            %li ・体重
            %li ・B・W・Hサイズ
          .audition-wrapper__contents__main__text
            上記を履歴書に明記の上、写真2枚（バストアップ・全身1枚ずつ）を貼付して応募送付先まで郵送して下さい。
          %ul.audition-wrapper__contents__main__list
            %li ※写真は撮影後3ヶ月以内
            %li ※面接にお越しいただきたい方のみ、こちらからご連絡差し上げます。
            %li ※応募書類の返却は致しませんので、ご了承下さい。
      %dl.article
        %dt 選考方法
        %dd
          %ul.audition-wrapper__contents__main__list
            %li ・第１次審査 ＝ 書類選考 (合格者のみ通知)
            %li ・第２次審査 ＝ 面接選考
      %dl.article
        %dt 応募送付先
        %dd
          %ul.audition-wrapper__contents__main__list
            %li 〒107-0052
            %li 東京都港区赤坂2-15-8 メインステージ赤坂302
            %li コロンコロン株式会社「新人募集係」
= render 'homes/footer'

app/views/company/index.html.haml
= render 'homes/header'
.rental-index
  coming soon...

app/views/contact/index.html.haml
= render 'homes/header'
お問い合わせ

app/views/homes/_audition_block.html.haml
= link_to audition_index_path, class: "btn-audition-block" do
  .audition_block
    .audition_block__title
      = icon('far', 'file-alt')
      Audition
    .audition_block__sub-title
      オーディションについて
    .audition_block__list
      Talent･Model･Artist･Actor･Actress
      

app/views/homes/_footer.html.haml
.footer
  .footer__contents
    .footer__contents__contact
      .footer__contents__contact__title
        Contact
      .footer__contents__contact__mail
        = link_to "mailto:coroncoron@coron2.jp", class: "btn-mail" do
          = icon('fas', 'envelope')
          問い合わせ
    .footer__contents__access
      .footer__contents__access__title
        Access
      .footer__contents__access__address-box
        .footer__contents__access__address-box__company.footer-address
          コロンコロン株式会社
        .footer__contents__access__address-box__address.footer-address
          〒107-0052　東京都港区赤坂2-15-8 メインステージ赤坂302
        .footer__contents__access__address-box__train.footer-address
          東京メトロ千代田線　赤坂駅より徒歩2分
          %br/
          各線　溜池山王駅より徒歩8分
          %br/
          東京メトロ丸ノ内線　赤坂見附駅より徒歩10分
        .footer__contents__access__address-box__english
          2-15-8 mainStage Bld.302, Akasaka, Shibuya-ku, Tokyo, 107-0052, Japan

      %iframe{:allowfullscreen => "", "aria-hidden" => "false", :frameborder => "0", :height => "300", :src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.2281677690335!2d139.73556595130802!3d35.67138343802122!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b86c623ffff%3A0x2712f9000b7837f1!2z44Oh44Kk44Oz44K544OG44O844K46LWk5Z2C!5e0!3m2!1sja!2sjp!4v1588794622792!5m2!1sja!2sjp", :style => "border:0;", :tabindex => "0", :width => "700"}

app/views/homes/_header.html.haml
.header
  .header__block
    = link_to "", root_path, class: "header__block__logo"
    .header__block__list
      = link_to "talent", talents_path, class: "header__block__list__talent", id: "header_li"
      = link_to "news", news_index_path, class: "header__block__list__news",id: "header_li"
      = link_to "audition", audition_index_path, class: "header__block__list__audition",id: "header_li"
      = link_to "company", company_index_path, class: "header__block__list__company",id: "header_li"

app/views/homes/_home_contents-news.html.haml
.home_contents__box__right__news
  .home_contents__box__right__news__block
    .home_contents__box__right__news__block__title
      %i.far.fa-newspaper.fa-1em.home_contents__box__right__news__block__title__icon
      .home_contents__box__right__news__title__block__text News
    .home_contents__box__right__news__block__article
      - @news.each do |n|
        .home_contents__box__right__news__block__article__category
          %span 
            = n.category
        .home_contents__box__right__news__block__article__text 
          = "<高村義文> | #{n.text}"
          -# ＜岡本莉音＞2020.5.1「Seventeen」2020年6月号
    .home_contents__box__right__news__block__bottom
      = link_to "もっと見る", news_index_path, class: "home_contents__box__right__news__block__bottom__news-link"

app/views/homes/_home_contents-slide.html.haml
.swiper-container
  .swiper-wrapper
    .swiper-slide
      = image_tag 'model1.jpeg', class: "swiper-slide"
    .swiper-slide
      = image_tag 'model2.jpeg', class: "swiper-slide"
    .swiper-slide
      = image_tag 'model3.jpeg', class: "swiper-slide"
    .swiper-slide
      = image_tag 'model4.jpeg', class: "swiper-slide"

  .swiper-pagination

app/views/homes/_home_contents.html.haml
.home_contents
  .home_contents__box
    .home_contents__box__left
      = render 'audition_block'
      = render 'menu-side-container'
      = render 'twitter_timeline'
    .home_contents__box__right
      = render 'home_contents-slide'
      = render 'home_contents-news'

app/views/homes/_menu-side-container.html.haml
.menu-side-container
  = link_to news_index_path, class: "btn-menu-side-container" do
    .menu-side-container__box
      .menu-side-container__box__new
        = icon('far', 'newspaper')
        News
      .menu-side-container__box__icon
        = icon('fas', 'chevron-right')
  = link_to company_index_path, class: "btn-menu-side-container" do
    .menu-side-container__box
      .menu-side-container__box__new
        = icon('far', 'building')
        Company Profile
      .menu-side-container__box__icon
        = icon('fas', 'chevron-right')
  = link_to audition_index_path, class: "btn-menu-side-container" do
    .menu-side-container__box
      .menu-side-container__box__new
        = icon('far', 'file-alt')
        Audition
      .menu-side-container__box__icon
        = icon('fas', 'chevron-right')
  -# = link_to "#", class: "btn-menu-side-container" do
  -#   .menu-side-container__box
  -#     .menu-side-container__box__new
  -#       = icon('far', 'user')
  -#       Recruit
  -#     .menu-side-container__box__icon
  -#       = icon('fas', 'chevron-right')

app/views/homes/_top_images.html.haml
.home-images
  .home-images__box

app/views/homes/_twitter_timeline.html.haml
.twitter_timeline
  %a.twitter-timeline{"data-height" => "500", "data-theme" => "light", :href => "https://twitter.com/AbeShinzo?ref_src=twsrc%5Etfw"} Tweets by AbeShinzo
  %script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}

app/views/homes/index.html.haml
.wrapper
  = render 'header'
  = render 'top_images'
  = render 'home_contents'
  = render 'footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Coroncoron
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    "https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css"
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.min.js"
  %body
    
    = yield

app/views/news/index.html.haml
= render 'homes/header'
.news-content
  .news-content__title NEWS
  .news-content__list
    - @news.each do |n|
      .news-content__list__article
        .news-content__list__article__date
          = n.date
        .news-content__list__article__bottom
          .news-content__list__article__bottom__talent-name
            高村義文
            -# = n.talent.name
          .news-content__list__article__bottom__text
            = n.text

  .pagenate
    = paginate @news

app/views/talents/_show_left.html.haml
.show-talent-image
  .show-talent-image__main
    = image_tag ("#{@talent.images[0].url.url}"), class: "large-img"
  .show-talent-image__sub
    .show-talent-image__sub__image
      = image_tag ("#{@talent.images[0].url.url}"), class: "small-img"
    .show-talent-image__sub__image
      - if @talent.images[1].present?
        = image_tag ("#{@talent.images[1].url.url}"), class: "small-img"
      - else
        .blanc-img
    .show-talent-image__sub__image
      - if @talent.images[2].present?
        = image_tag ("#{@talent.images[2].url.url}"), class: "small-img"
      - else
        .blanc-img

app/views/talents/_show_media.html.haml
.show-talent-media
  .show-talent-media__list-box
    %ul
      %li
        TV
      %li
        雑誌
      %li
        舞台
      %li
        イベント
.show-talent-content
  2020.4.22「ニコ☆プチ」2020年6月号

app/views/talents/_show_right.html.haml
.talent-show__detail
  .talent-show__detail__header
    %h2
      = @talent.role
    %h1
      = @talent.l_name
      = @talent.f_name
    %p
      = @talent.e_l_name
      = @talent.e_f_name
  %table.talent-show__detail__data
    - unless @talent.dob.blank?
      %tr
        %th DATE OF BIRTH
        %td
          = "#{@talent.dob.strftime('%Y年%m月%d日')}"
    %tr
      %th SIZE
      %td
        - unless @talent.height.blank?
          = "T#{@talent.height}"
        - unless @talent.chest_bust.blank?
          = "/C#{@talent.chest_bust}"
        - unless @talent.waist.blank?
          = "/W#{@talent.waist}"
        - unless @talent.hips.blank?
          = "/H#{@talent.hips}"
        - unless @talent.shoes.blank?
          = "/S#{@talent.shoes}"
    - unless @talent.birthplace.blank?
      %tr
        %th BIRTHPLACE
        %td
          = "#{@talent.birthplace}"
    - unless @talent.blood.blank?
      %tr
        %th BLOOD TYPE
        %td
          = "#{@talent.blood}"
          

app/views/talents/index.html.haml
= render 'homes/header'
.talent-index
  .talent-index__talent-list
    - @talents.each do |t|
      .talent-index__talent-list__box
        = link_to talent_path(t.id) do
          = image_tag(t.images[0].url.url, class: "talent-index__talent-list__box__image")
        .talent-index__talent-list__box__role
          = t.role
        .talent-index__talent-list__box__name
          = t.l_name
          = t.f_name
        .talent-index__talent-list__box__eng-name
          = t.e_l_name
          = t.e_f_name
= render 'homes/footer'

app/views/talents/show.html.haml
= render 'homes/header'
.talent-show-wrapper
  .talent-show-wrapper__contents
    .talent-show-wrapper__contents__left
      = render 'show_left'
    .talent-show-wrapper__contents__right
      = render 'show_right'
  .talent-show-wrapper__media-contents
    = render 'show_media'
  .talent-show-wrapper__return-talents
    = link_to talents_path, class: "btn-talents" do
      タレント一覧へ
= render 'homes/footer'